version: "3"

services:
  web:
    container_name: mealog-frontend
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - web

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  web:
    external: true
